project:
  type: website
  output-dir: docs

website:
  title: Ihnwhi Heo Website
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



