project:
  type: website
  output-dir: docs

website:
  title: Quantitative Psychology
  description: "Assistant Professor of Quantitative Psychology"
  site-url: https://ihnwhiheo.github.io
  favicon: img/iheofavi.png
  open-graph: true
  navbar:
    title: "Ihnwhi Heo, Ph.D."
#    logo: img/logo_heo.png
    left:
      - href: index.qmd
        text: Profile
      - href: articles.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
#      - talks.qmd
  google-analytics: 
    tracking-id: "G-FHK2YX1CJQ" # "357254636" 
  page-footer:
    center: "&copy; Ihnwhi Heo, 2025&ndash;2026"

format:
  html:
    theme:
      - simplex
      - navy-theme.scss
#      light: simplex
#      dark: darkly
    css: styles_navy.css
    toc: true
    page-layout: full

# mainfont: CHOOSEFONT

# backgroundcolor: white

