project:
  type: website
  output-dir: docs

website:
  title: Ihnwhi's Website
  description: "Ph.D. in Quantitative Methods, Measurement, and Statistics"
  favicon: img/iheofavi.png
  navbar:
#    logo: img/logo_heo.png
    left:
      - href: index.qmd
        text: Profile
      - articles.qmd
      - talks.qmd
  google-analytics: 
    tracking-id: "G-FHK2YX1CJQ" # "357254636" 
  page-footer:
    center: "&copy; Ihnwhi Heo, 2025"

format:
  html:
    theme: simplex
#      light: simplex
#      dark: darkly
    css: styles_navy.css
    toc: true
    page-layout: full

# mainfont: CHOOSEFONT

# backgroundcolor: white

