---
title: "Articles"
---

This page provides a list of peer-reviewed journal articles and manuscripts currently under review in both methodological and applied journals. For potential collaborations or to discuss research ideas, please reach out to me via [email](mailto:ihnwhi.heo@gmail.com).

## Under Review

- Pfadt, J. M., Bartoš, F., Godmann, H. R., Waaijers, M., Groot, L., **Heo, I.**, Mensink, L., Nak, J., de Ruiter, J. P., Sarafoglou, A., Siepe, B., Arena, G., Akrong, E., Aust, F., van den Bergh, D., Brenner, W., Doekemeijer, R., Donzallaz, M. C., van Doorn, J., Echevarria, N. O., Finneman, A., Geller, G., Hato, T., Koskinen, E., Krijgsman, B., Kulbe, L., Lüken, M., Marsman, M., Ott, V. L., Pawel, S., Piestrak, O., de Ron, J., Sekulovski, N., Serry, M., Stefanów, A., Stevenson, N., Sadowski, B., Sopuch, M., Vasileiou, A., Visser, I., Völler, M., Wiechert, S., de Wit, K., Wuth, J., \& Wagenmakers, E.-J. (submitted). A methodological metamorphosis: The rapid rise of Bayesian inference and open science practices in psychology.
  - [Preprint](https://doi.org/10.31234/osf.io/ck3js_v1)
  
- Peña, M., **Heo, I.**, Depaoli, S., \& Zawadzki, M. J. (submitted). Identifying screening-level predictors of enrollment in a mobile mindfulness meditation trial: A Bayesian model-averaged logistic regression approach.
  - [Preprint](https://preprints.jmir.org/preprint/86696)

- Jia, F., **Heo, I.**, Depaoli, S., \& Li, Y. (revise & resubmit). Latent mediation analysis with missing data: A comparison of Bayesian SEM and Monte Carlo–adjusted frequentist approaches.

## In Press

- **Heo, I.**, Jia, F., \& Depaoli, S. (in press). Bayesian variable selection via shrinkage priors in growth mixture models [Abstract]. *Multivariate Behavioral Research*.
  - PDF is forthcoming.

## 2025

- Depaoli, S., **Heo, I.**, Jauregui, M., Liu, H., \& Jia, F. (2025). A comprehensive evaluation of model selection indices for class enumeration in Bayesian latent growth mixture models. *Structural Equation Modeling: A Multidisciplinary Journal*. Advance online publication. [https://doi.org/10.1080/10705511.2025.2566135](https://doi.org/10.1080/10705511.2025.2566135)
  - [PDF](files/papers/Depaoli2025_Comprehensive.pdf)
  - [OSF](https://osf.io/2resf/)

- **Heo, I.**, Simons, J.-W., \& Liu, H. (2025). A tutorial on Bayesian model averaging for exponential random graph models. *British Journal of Mathematical and Statistical Psychology*. Advance online publication. [https://doi.org/10.1111/bmsp.70007](https://doi.org/10.1111/bmsp.70007)
  - [PDF](files/papers/Heo2025_Tutorial.pdf)
  - [OSF](https://osf.io/g9eq4/)

- **Heo, I.**, Liu, R., Liu, H., Depaoli, S., \& Jia, F. (2025). A study of latent state-trait theory framework in piecewise growth models. *Applied Psychological Measurement*. Advance online publication. [https://doi.org/10.1177/01466216251360565](https://doi.org/10.1177/01466216251360565)
  - [PDF](files/papers/Heo2025_Study.pdf)
  - [OSF](https://osf.io/dmtus/)

- **Heo, I.**, Jia, F., \& Depaoli, S. (2025). Recovering knot placements in Bayesian piecewise growth models with missing data. *Behavior Research Methods, 57*(7). 1--27. [https://doi.org/10.3758/s13428-025-02716-0](https://doi.org/10.3758/s13428-025-02716-0)
  - [PDF](files/papers/Heo2025_Recovering.pdf)
  - [OSF](https://osf.io/j46bf/)

- Liu, H., **Heo, I.**, Ivanov, A., \& Depaoli, S. (2025). Model assumption violations in Bayesian latent mediation analysis: An exploration of Bayesian SEM fit indices and PPP. *Structural Equation Modeling: A Multidisciplinary Journal, 32*(5). 866--896. [https://doi.org/10.1080/10705511.2025.2503789](https://doi.org/10.1080/10705511.2025.2503789)
  - [PDF](files/papers/Liu2025_Model.pdf)

- Liu, H., **Heo, I.**, Depaoli, S., \& Ivanov, A. (2025). Parameter recovery for misspecified latent mediation models in the Bayesian framework. *Structural Equation Modeling: A Multidisciplinary Journal, 32*(4). 618--637. [https://doi.org/10.1080/10705511.2025.2475490](https://doi.org/10.1080/10705511.2025.2475490) 
  - [PDF](files/papers/Liu2025_Parameter.pdf)
	
- **Heo, I.**, Pfadt, J. M., \& Wagenmakers, E.-J. (2025). Contributed discussion of "Sparse Bayesian factor analysis when the number of factors is unknown". *Bayesian Analysis, 20*(1). 295--296. [https://doi.org/10.1214/24-BA1423](https://doi.org/10.1214/24-BA1423)
  - [PDF](files/papers/Heo2024_Contributed.pdf)


## 2024

- **Heo, I.**, Depaoli, S., Jia, F., \& Liu, H. (2024). Bayesian approach to piecewise growth mixture modeling: Issues and applications in school psychology. *Journal of School Psychology, 107*. 101366. [https://doi.org/10.1016/j.jsp.2024.101366](https://doi.org/10.1016/j.jsp.2024.101366) 
  - [PDF](files/papers/Heo2024_Bayesian.pdf)
  - [OSF](https://osf.io/udrb8/)

- **Heo, I.**, Jia, F., \& Depaoli, S. (2024). Performance of model fit and selection indices for Bayesian piecewise growth modeling with missing data. *Structural Equation Modeling: A Multidisciplinary Journal, 31*(3). 455--476. [https://doi.org/10.1080/10705511.2023.2264514](https://doi.org/10.1080/10705511.2023.2264514) 
  - [PDF](files/papers/Heo2024_Performance.pdf)
  - [OSF](https://osf.io/agn4x/)


## 2023

- Depaoli, S., Jia, F., \& **Heo, I.** (2023). Detecting model misspecification in Bayesian piecewise growth models. *Structural Equation Modeling: A Multidisciplinary Journal, 30*(4). 574--591. [https://doi.org/10.1080/10705511.2022.2144865](https://doi.org/10.1080/10705511.2022.2144865) 
  - [PDF](files/papers/Depaoli2023_Detecting.pdf)
  - [OSF](https://osf.io/myrds/)

- **Heo, I.**, Jia, F., \& Depaoli, S. (2023). Book review of *Longitudinal structural equation modeling with Mplus: A latent state-trait perspective* by Geiser. *Psychometrika, 88*(2), 733--737. [https://doi.org/10.1007/s11336-022-09897-z](https://doi.org/10.1007/s11336-022-09897-z)
  - [PDF](files/papers/Heo2023_Book.pdf)

- Liu, R., **Heo, I.**, Liu, H., Shi, D., \& Jiang, Z. (2023). Applying negative binomial distribution in diagnostic classification models for analyzing count data. *Applied Psychological Measurement, 47*(1), 64--75. [https://www.doi.org/10.1177/01466216221124604](https://www.doi.org/10.1177/01466216221124604)
  - [PDF](files/papers/Liu2023_Applying.pdf)
  - [Code](files/papers/Liu2023_Applying_Code.pdf)

